# Generated by Django 4.1.7 on 2023-03-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_captured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captured',
            name='date',
            field=models.DateField(verbose_name='Captured Date'),
        ),
    ]
